version: '3.8'

services:
  db:
    image: postgres:14
      container_name: coursiva_prod_db
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


volumes:
  postgres_data:
