version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: local_secret
      POSTGRES_PASSWORD: local_secret
      POSTGRES_DB: local_secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - default

volumes:
  postgres_data: