# Generated by Django 5.2.3 on 2025-06-17 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcards_json', models.JSONField()),
                ('uuid_flashcard', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mindmap_json', models.JSONField()),
                ('uuid_mindmap', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100)),
                ('uuid_playlist', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('playlist_url', models.URLField()),
                ('playlist_thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_json', models.JSONField()),
                ('uuid_quiz', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('questions_count', models.PositiveIntegerField(blank=True, null=True)),
                ('quiz_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score_percentage', models.FloatField(blank=True, null=True)),
                ('correct_answers_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user_answers', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('uuid_video', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_string', models.CharField(blank=True, max_length=20, null=True)),
                ('summary', models.TextField()),
                ('full_transcript', models.TextField(blank=True, null=True)),
                ('timecode_transcript', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
