# Generated by Django 5.2.3 on 2025-06-17 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.playlist'),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='main.video'),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='mindmap_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmaps', to='main.video'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='main.video'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('playlist_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('video_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('user', 'quiz_video')},
        ),
        migrations.AlterUniqueTogether(
            name='mindmap',
            unique_together={('user', 'mindmap_video')},
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('uuid_flashcard', 'user')},
        ),
    ]
