# Generated by Django 5.2.1 on 2025-06-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_video_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='summary',
            field=models.TextField(default='fix'),
            preserve_default=False,
        ),
    ]
