# Generated by Django 5.2.1 on 2025-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_video_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
