# Generated by Django 5.2.1 on 2025-06-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_playlist_playlist_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='timecode_transcript',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
