# Generated by Django 5.2.1 on 2025-06-08 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_playlist_user_video_user_alter_video_duration_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='uuid_playlist',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='uuid_video',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
