# Generated by Django 5.2.1 on 2025-06-08 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_playlist_uuid_playlist_video_uuid_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcards_json', models.JSONField()),
                ('uuid_flashcard', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('flashcard_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='main.video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('uuid_flashcard', 'user')},
            },
        ),
    ]
