# Generated by Django 5.2.1 on 2025-06-11 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_mindmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_json', models.JSONField()),
                ('uuid_quiz', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('questions_count', models.PositiveIntegerField(blank=True, null=True)),
                ('quiz_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='main.video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('uuid_quiz', 'user')},
            },
        ),
    ]
