# Generated by Django 5.2.1 on 2025-06-11 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('user', 'quiz_video')},
        ),
    ]
