# Generated by Django 5.2.1 on 2025-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_answers_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
