# Generated by Django 5.2.1 on 2025-06-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_url',
            field=models.URLField(default='https://youtube.com/playlist?list=PLhQjrBD2T383q7Vn8QnTsVgSvyLpsqL_R&si=TGOVjHhkUXqfloQs'),
            preserve_default=False,
        ),
    ]
