# Generated by Django 5.2.1 on 2025-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='full_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
