# Generated by Django 5.2.1 on 2025-06-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_video_full_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
